DROP TABLE IF EXISTS Projects0;
DROP TABLE IF EXISTS Projects2;
DROP TABLE IF EXISTS Projects3;
DROP TABLE IF EXISTS Projects4;
DROP TABLE IF EXISTS Projects1;

CREATE TABLE Projects1 (
       MID INTEGER NOT NULL,
       MN VARCHAR(50) NOT NULL,
       PRIMARY KEY (MID)
);

CREATE TABLE Projects2 (
       ID INTEGER NOT NULL,
       MID INTEGER NOT NULL,
       PRIMARY KEY (ID),
       FOREIGN KEY (MID) REFERENCES Projects1 (MID)
);

CREATE TABLE Projects3 (
       PID INTEGER NOT NULL, 
       PN VARCHAR(50) NOT NULL, 
       PRIMARY KEY (PID)
);

CREATE TABLE Projects4 (
       SID INTEGER NOT NULL, 
       SN VARCHAR(50) NOT NULL, 
       PRIMARY KEY (SID)
);

CREATE TABLE Projects0 (
       ID INTEGER NOT NULL,
       PID INTEGER NOT NULL, 
       SID INTEGER NOT NULL, 
       PRIMARY KEY (ID, PID, SID),
       FOREIGN KEY (ID) REFERENCES Projects2 (ID),
       FOREIGN KEY (PID) REFERENCES Projects3 (PID),
       FOREIGN KEY (SID) REFERENCES Projects4 (SID)
);

INSERT INTO Projects1
SELECT DISTINCT MID, MN
FROM Projects;

INSERT INTO Projects2
SELECT DISTINCT ID, MID
FROM Projects;

INSERT INTO Projects3
SELECT DISTINCT PID, PN
FROM Projects;

INSERT INTO Projects4
SELECT DISTINCT SID, SN
FROM Projects;

INSERT INTO Projects0
SELECT DISTINCT ID, PID, SID
FROM Projects;

