SELECT COUNT(*)
FROM (
  SELECT AIRPORT.AIRPORT,
      (SELECT COUNT(FLIGHTS.ARR) FROM FLIGHTS WHERE FLIGHTS.ARR = AIRPORT.AIRPORT) AS ARR_COUNT,
      (SELECT COUNT(FLIGHTS.DEP) FROM FLIGHTS WHERE FLIGHTS.DEP = AIRPORT.AIRPORT) AS DEP_COUNT
  FROM AIRPORT
  INNER JOIN COUNTRY ON AIRPORT.COUNTRY = COUNTRY.COUNTRY
  WHERE COUNTRY.REGION = 'EU'
) AS subquery
WHERE ARR_COUNT > 0 AND DEP_COUNT > 0;