SELECT COUNT(*) FROM FLIGHTS
INNER JOIN AIRPORT ON FLIGHTS.DEP = AIRPORT.AIRPORT
INNER JOIN COUNTRY ON AIRPORT.COUNTRY = COUNTRY.COUNTRY
INNER JOIN AIRCRAFT ON FLIGHTS.ACTYPE = AIRCRAFT.ACTYPE
WHERE AIRCRAFT.CAPACITY > 300
AND COUNTRY.REGION = 'AS'