-- Q1
--MY SOLUTION:
SELECT DISTINCT(PEOPLE.PID), PEOPLE.PNAME FROM PEOPLE
INNER JOIN ACCOUNTS ON PEOPLE.PID = ACCOUNTS.PID
INNER JOIN BILLS ON PEOPLE.PID = BILLS.PID
WHERE PEOPLE.PGENDER = 'F' 
AND BILLS.BAMOUNT > ACCOUNTS.ABALANCE + ACCOUNTS.AOVER;

-- Q2
-- MY SOLUTION:
SELECT PEOPLE.PID, PEOPLE.PNAME, BILLS.BID FROM PEOPLE
INNER JOIN ACCOUNTS ON PEOPLE.PID = ACCOUNTS.PID
INNER JOIN BILLS ON PEOPLE.PID = BILLS.PID
WHERE PEOPLE.PGENDER = 'M' AND BILLS.BAMOUNT > ACCOUNTS.ABALANCE;

-- Q3
--MY SOLUTION:
SELECT DISTINCT(PEOPLE.PID), PEOPLE.PNAME FROM PEOPLE
INNER JOIN ACCOUNTS ON PEOPLE.PID = ACCOUNTS.PID
WHERE PEOPLE.PHEIGHT > 1.75 OR ACCOUNTS.ABALANCE < 0;

-- Q4
-- MY SOLUTION:
SELECT DISTINCT(PEOPLE.PID), PEOPLE.PNAME FROM PEOPLE
INNER JOIN ACCOUNTS ON PEOPLE.PID = ACCOUNTS.PID
WHERE PEOPLE.PHEIGHT > 1.75 OR PEOPLE.PID IN (
SELECT PID FROM ACCOUNTS WHERE ABALANCE < 0
);